complexity:
  LongMethod:
    active: true
    excludes: '**/generated/**'
    threshold: 150
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    ignoreDefaultParameters: true
    functionThreshold: 9
    constructorThreshold: 10
    ignoreAnnotated: [ 'Inject', 'Composable' ]

style:
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'DarkLightModePreviews', 'Composable' ]
  MagicNumber:
    ignoreEnums: true
    ignoreAnnotated: [ 'Composable' ]
    ignorePropertyDeclaration: true
  NewLineAtEndOfFile:
    active: true
    excludes: '**/generated/**'
  MaxLineLength:
    active: true
    excludes: '**/generated/**'

naming:
  ClassNaming:
    excludes: '**/generated/**'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
    excludes: '**/generated/**'
