name: App-Commander - PR-Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  pr_check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run code analysis-tools and execute unit-tests.
        run: |
          ./gradlew detekt detektJvmMain --no-build-cache
          ./gradlew ktlintCheck --no-build-cache
          ./gradlew allTests --no-build-cache
          ./gradlew runCodeCoverage --no-build-cache
          
      - name: Archive generated screenshots from unit-tests + HTML report.
        uses: actions/upload-artifact@v4
        if: success() || failure() # always run even if the previous step are failing.
        with:
          name: screenshots-files
          path: |
            **/build/reports/tests/screenshots/*.png
            **/build/reports/tests/jvmTest/**
            **/src/commonTest/kotlin/de/joz/appcommander/**/*.png
            
      - name: Publish test report.
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous steps are failing.
        with:
          report_paths: '**/build/test-results/jvmTest/TEST-*.xml'
          
      - name: Run lint formatting if previous steps are failing.
        if: failure()
        run: |
          ./gradlew ktlintFormat --no-build-cache

      - name: Commit and push screenshots and lint formatting changes.
        if: failure()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: apply lint formatting and update screenshots" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
