# This is a basic workflow to help you get started with Actions

name: PR_checks

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run code analysis-tools and execute unit-test.
        run: |
          ./gradlew detekt detektJvmMain --no-build-cache
          ./gradlew ktlintCheck --no-build-cache
          ./gradlew :composeApp:cleanJvmTest :composeApp:jvmTest --no-build-cache
          ./gradlew allTests --no-build-cache
