name: App-Commander - PR-Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr_check_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run code analysis-tools and execute unit-tests.
        run: |
          ./gradlew detekt detektJvmMain --no-build-cache
          ./gradlew ktlintCheck --no-build-cache
          ./gradlew allTests --no-build-cache
          ./gradlew runCodeCoverage --no-build-cache
          
      - name: Archive generated screenshots from unit-tests + HTML report.
        uses: actions/upload-artifact@v4
        if: success() || failure() # always run even if the previous step are failing.
        with:
          name: screenshots-files
          path: |
            **/build/reports/tests/screenshots/*.png
            **/build/reports/tests/jvmTest/**
            **/src/commonTest/kotlin/de/joz/appcommander/**/*.png
            
      - name: Publish test report.
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous steps are failing.
        with:
          report_paths: '**/build/test-results/jvmTest/TEST-*.xml'
          
      - name: Commit and push screenshots changes.
        uses: stefanzweifel/git-auto-commit-action@v5
        if: failure()
        with:
          commit_message: "ci: apply lint formatting and update screenshots"
          # Optional: specific files to add
          # file_pattern: '*.png'
