name: App-Commander - PR-Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  pr_check_build:
    # if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run code analysis-tools and execute unit-test.
        run: |
          ./gradlew detekt detektJvmMain --no-build-cache
          ./gradlew ktlintCheck --no-build-cache
          ./gradlew allTests --no-build-cache
